matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

notifications:
  email: false

deploy:
  provider: script
  script: npm run electron-pack
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
  - master