platform:
  - x64

branches:
  only:
    - main
install:
  - ps: Install-Product node Current x64
  - npm install npm@latest -g
  - npm install -g electron-builder
  - npm install
build_script:
  - npm run electron-pack
